#!/usr/bin/env bash
# simple example showing how the AI could "write" files and then package them
# into a zip or apk.  In practice the prompts would drive what files are created.

set -e
OUTDIR=$(mktemp -d)

# placeholder: create some text files
cat <<'EOF' > "$OUTDIR/hello.txt"
This file was generated by the AI environment script.
EOF

# create a dummy AndroidManifest.xml so that zip -> apk is possible
cat <<'EOF' > "$OUTDIR/AndroidManifest.xml"
<manifest package="com.example.generated">
    <application android:label="Generated App" />
</manifest>
EOF

# package as zip
ZIPNAME="ai_world_$(date +%s).zip"
zip -r "$ZIPNAME" -j "$OUTDIR"/*
echo "Created $ZIPNAME"

# if you wantapk, just change extension to .apk; Android will still open it as
# a zip, but you could add compiled .dex files etc.  This is purely illustrative.
APKNAME="ai_world_$(date +%s).apk"
cp "$ZIPNAME" "$APKNAME"
echo "Created $APKNAME (identical to zip)"

echo "Clean up"
rm -rf "$OUTDIR"
